# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
#use frameworks!

target 'Xpress Order' do
    pod 'SVProgressHUD' #, :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
    pod 'DWBubbleMenuButton', '~> 1.0.1'
end

